### ISSUE TITLE
REST or AlwaysON Protocoll, HTTP or HTTPS

### ISSUE THREAD

**Issue by stefanbode** [hms-networks/flexy-thingworx-connector#15]
hi @alexjhawk ,

we are trying to establish a direct connection between the device and a thingworx server. If I understand the code correctly it do not use the Java SDK and the AlwaysOn protocol. For me it look like it try REST pushes with the variable values. Correct?

Second: I do not see a port I can add to the server name. What port is the software using by default? Also I'm not sure if the communication is https or HTTP. it looks like HTTP, but I assume it is https because this is an internet communication.

Third: https certificates. Are you accepting any https certificate or do you check against the java root certificates and ensure the chain in valid.

**Comment by alexjhawk** [comment]
@stefanbode,

1. You are correct, the Flexy device does not use the Thingworx Java SDK or the AlwaysOn protocol. It sends the values to a service on Thingworx using the REST API.

2. If no port is specified, the default is used for the transport type specified (HTTP or HTTPS). The default configuration file does not specify a port or http/https. Both of those can be specified in the `ThingworxIP` field to form something like "https://1.2.3.4:8088"

3. The Ewon java application performs all HTTP requests using the Ewon developer kit (see: [developer.ewon.biz](developer.ewon.biz)). All HTTPS requests are verified by the Ewon using its internal root certificates.

**Comment by alexjhawk** [comment]
Hi @stefanbode,

Version 1.1 of the connector has been released this morning and includes significant stability and organization modifications. It can be downloaded from https://github.com/hms-networks/flexy-thingworx-connector/releases. 

As a result, many previously identified questions and bugs have been resolved, so I'm going to close this open issue.

If you have any questions or run into issues with version 1.1, feel free to file a new GitHub Issue or reach out to me.
