### ISSUE TITLE
Talk2MSyncData does pass on correct basetype to InsertDataPoint

### ISSUE THREAD

**Issue by tom-roger** [hms-networks/flexy-thingworx-connector#23]
The code is using datapoint.dataType, while the correct syntax is tag.dataType.  Consequence is that all properties are updated with basetype = "NUMBER". The code is failing and the log is populated with "Unknown data type" for all values.    
        
                // Get tag data type
                var tagType;
                if (datapoint.dataType === "Int") {
                    tagType = TW_DATA_TYPE_INTEGER;
                } else if (datapoint.dataType === "Bool") {
                    tagType = TW_DATA_TYPE_BOOLEAN;
                } else if (datapoint.dataType === "Float") {
                    tagType = TW_DATA_TYPE_NUMBER;
                } else if (datapoint.dataType === "UInt") {
                    tagType = TW_DATA_TYPE_NUMBER;
                } else {
                    logger.warn("Unknown data type (" + datapoint.dataType + ") for tag: " + tag.name);
                    tagType = TW_DATA_TYPE_NUMBER;
                }

**Comment by it-hms** [comment]
@tom-roger 
Thanks for bringing this to our attention.

Here's a link: 
https://github.com/hms-networks/flexy-thingworx-connector/blob/03562d00143068f310a76a39b18950829c976149/thingworx-import/Entities.xml#L341

**Comment by alexjhawk** [comment]
Hi @tom-roger,

This issue has been resolved in version 1.1.1, which has just been released to GitHub releases (https://github.com/hms-networks/flexy-thingworx-connector/releases/tag/1.1.1).

Thank you for bringing this issue to our attention.
