### ISSUE TITLE
Dashboards with Real-Time Info

### ISSUE THREAD

**Issue by Tom-HMS** [hms-networks/flexy-thingworx-connector#29]
The current solution does not support an easy way to read real-time values via a M2Web read.  A new service should be created call ReadEwonTagValue for the GenericEwonDeviceTalk2M.  This service should perform a read of a single tag value.

**Comment by Tom-HMS** [comment]
Thingworx requires a service for each data type.  As a result, we need to create a ReadEwonTagValueNumber and ReadEwonTagValueInteger.  I used the current UpdateEwonTagValue read back check function as a reference this code reads the entire tag list for a Flexy device at one time.  This is ideal because M2Web tracks the number of calls not the number of tag reads.  The new function should accept an array of tag names so the result can be an array of tag results.   It is not clear to me how this should be done in Thingworx.  

Additionally the simple parsing command in the current function uses the fact that the string length of the variable being written is known and can be used to determine the end of the string when reading data back.  This is not possible when doing a read.  A better parsing function needs to look for the "}" to determine the end of the value string.

**Comment by it-hms** [comment]
@Tom-HMS 
I believe that we need a little more definition for this service or set of services. The need, as you mention is to read real-time values.  What should be done with the results of the read? This service could return JSON. Or it could update thing properties, but this assumes that the properties are already created. What would you prefer?

**Comment by Tom-HMS** [comment]
My new service (ReadEwonTagValueaNumber) is in a thing based on the GenericEwonDeviceTalk2M thing template.  At least one of these things exists for each Flexy, it is possible to represent a single Flexy with multiple things, each thing having sub set of the tags in that Flexy.  The inputs to my service are tagName the output is a result (number).  One issue is the M2Web function I am using reads all of the tags on the Flexy and tosses out all but one value.  It would be better to read back all of the data into an INFOTABLE.  If we do that we can eliminate the tagName input and use the tag name to index the table in the mashup but it is not clear to me how to use the "Selected Row(s)" feature in the binding process.

**Comment by alexjhawk** [comment]
@Tom-HMS,

I have completed a restructure and update of the services for M2Web read and write functionality on Things in Thingworx. To reduce the need for an individual M2Web API call to retrieve each individual tag's value, I've included a parameter on the read services called "useCached". When this value is set to true, it will parse and read the appropriate value from the last M2Web call.
