### ISSUE TITLE
Can't get v1.2 .jar to run

### ISSUE THREAD

**Issue by scottwstevens** [hms-networks/flexy-thingworx-connector#38]
I have went through the steps multiple times without success, even reset with all the check-boxes in Erase & Format.  Never get the *config.json in the /usr folder and no realtime log (JVM) entries.  I put the older v1.1.1 JAR and jvmrun in /usr, and after reboot I immediately see the config.json file as well as the "Starting Ewon Thingworx Connector 1.0" JVM log event.

**Comment by TomKimsey** [comment]
@scottwstevens thank you for bringing this to our attention. I looked into it and it looks like the v1.2 release has invalid line endings in the jvmrun file. As a quick fix/test you should be able to use the v1.2 JAR and the v1.1.1 jvmrun file together and that should start the v1.2 connector.

**Comment by scottwstevens** [comment]
That worked.  Thanks for the quick reply!  
FYI, I posted first to HMS.how but then later after getting v1.1.1 to work I figured I should post here as well despite starting (2) threads on the topic.  Any thoughts / feedback on when to comment where?

**Comment by TomKimsey** [comment]
In general, usage and setup questions can get posted to hms.how. For bugs such as this one, posting on hms.how or the Github issues section are both appropriate.

**Comment by TomKimsey** [comment]
@scottwstevens I closed your hms.how ticket. The team is going to release v1.2.1 shortly that will fix this issue with the jvmrun file.

**Comment by alexjhawk** [comment]
Hi @scottwstevens,

The updated version of the connector, v1.2.1 is now available for download on the releases page.

See: https://github.com/hms-networks/flexy-thingworx-connector/releases/tag/v1.2.1
