### ISSUE TITLE
Inefficient locations for checks

### ISSUE THREAD

**Issue by Geniejohn** [hms-networks/flexy-thingworx-connector#65]
As of Release v3.2.1, the code in services InsertDataPoint and Talk2MSyncData makes very inefficient checks.

InsertDataPoint's 'run'-function gets called for each Ewon, for each Tag, for Each datapoint. The logic for checking if 'thing' exists for that Ewon is located in this 'run'-function. A better placement would be at the start of foreach Ewon, because it only needs to run one time per Ewon to serve its function. 

Same goes for the logic of handling new properties/tags, it is run for each datapoint instead of each tag.

### Inefficient Placement
![Inefficient Placement](https://user-images.githubusercontent.com/23278253/177156901-1e32dce4-8f40-4732-bacf-6762faa053c5.png)

### More Efficient Placement
![More Efficient Placement](https://user-images.githubusercontent.com/23278253/177157153-289a7edf-a732-41dc-9ead-a99308b7130a.png)

### Inefficient Placement of Tag-logic
![Inefficient Placement of Tag-logic](https://user-images.githubusercontent.com/23278253/177157397-1a810677-9ddf-420b-a78d-d8f22f9760d8.png)

### More Efficient Placement of Tag-logic
![More Efficient Placement of Tag-logic](https://user-images.githubusercontent.com/23278253/177157452-4b7e238c-f6f9-4e9f-97af-f0b295b8a6bc.png)

**Comment by it-hms** [comment]
feedback incorporated into release 3.3

**Comment by Geniejohn** [comment]
### Still Inefficient Placement
Code still checks if thing exists for each property, should be moved to above the property-loop:
![Inefficient Placement](https://i.imgur.com/gnrhpWZ.png)
